version: '3'

services:
  web:
    image: python:3.12
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
      git clone https://github.com/cesarlpb/learn-step-by-step.git /usr/src/app &&
      cd /usr/src/app &&
      pip install --no-cache-dir -r requirements.txt &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
